services:
  redis:
    image: redis:8-alpine
    container_name: discgolf_redis_local
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data_local:/data
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discgolf_api_local
    depends_on:
      - redis
    env_file:
      - .env.local.bridge
    ports:
      - "8001:8000"
    command:
      [
        "/bin/bash",
        "-c",
        "/app/bash_scripts/pre_start.sh && uv run uvicorn src.main:app --host 0.0.0.0 --port 8000",
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data_local:
